version: "3.8"
services: 
  mongodb:
    image: "mongo"
    volumes: 
      - data:/data/db
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: curtis
      # MONGO_INITDB_ROOT_USERNAME: secret
      # alternatively a file can be used for env variables such as follows:
      #env_file:
      #  - ./env/mongo.env 
  backend:
    image: curc0006/backend
    #build: ./backend
    ports:
      - "90:80"
    volumes:
      - logs:/app/logs
      #- ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: curtis
    # MONGO_INITDB_ROOT_USERNAME: secret
  frontend:
    image: curc0006/frontend
    #build: ./frontend
    ports: 
    - "3000:3000"
    # this is the docker-compose version of -it  
    # stdinn_open: true
    # tty: true
    depends_on: 
      - backend 

volumes:
  # only named columes must be specified here
  data:
  logs:
